#服务器端口
server:
  port: 10010

spring:
  application:
    name: demo-user
  cloud:
    nacos:
      discovery:
        namespace: ae865828-fed1-4ac7-9a7e-593a5c0ab1f1
        server-addr: 127.0.0.1:8848
        group: test
      config:
        file-extension: yaml
        namespace: ae865828-fed1-4ac7-9a7e-593a5c0ab1f1
        server-addr: 127.0.0.1:8848
        group: test
    sentinel:
      transport:
        dashboard: 127.0.0.1:6387
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: mysql
#    show-sql: true